services:
  daltonian:
    build:
      context: ./html/
      dockerfile: ../Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./html/:/usr/local/apache2/htdocs/
    container_name: daltonian_website
  non-bootstrap-daltonian:
    build:
      context: ./non-bootstrap/
      dockerfile: ../Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./non-bootstrap/:/usr/local/apache2/htdocs/
    container_name: non_bootstrap_daltonian
  non-bootstrap-daltonian-adjustable:
    build:
      context: ./non-bootstrap-adjustable/
      dockerfile: ../Dockerfile
    ports:
      - "8081:80"
    volumes:
      - ./non-bootstrap-adjustable/:/usr/local/apache2/htdocs/
    container_name: non_bootstrap_daltonian_adjustable
  non-bootstrap-daltonian-adjustable-no-svg-file:
    build:
      context: ./non-bootstrap-adjustable-no-svg-file/
      dockerfile: ../Dockerfile
    ports:
      - "8082:80"
    volumes:
      - ./non-bootstrap-adjustable-no-svg-file/:/usr/local/apache2/htdocs/
    container_name: non_bootstrap_daltonian_adjustable_no_svg_file
  non-bootstrap-daltonian-adjustable-no-svg-or-css-file:
    build:
      context: ./non-bootstrap-adjustable-no-svg-or-css-file/
      dockerfile: ../Dockerfile
    ports:
      - "8083:80"
    volumes:
      - ./non-bootstrap-adjustable-no-svg-or-css-file/:/usr/local/apache2/htdocs/
    container_name: non_bootstrap_daltonian_adjustable_no_svg_or_css_file
  non-bootstrap-daltonian-standalone:
    build:
      context: ./non-bootstrap-daltonian-standalone/
      dockerfile: ../Dockerfile
    ports:
      - "8084:80"
    volumes:
      - ./non-bootstrap-daltonian-standalone/:/usr/local/apache2/htdocs/
    container_name: non_bootstrap_daltonian_standalone
